merge dev into main

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,16 +1,21 @@
-# copied from https://github.com/EkuboProtocol/governance/actions
 name: Tests
 
 on:
   push:
     branches:
-      - "**"
+      - main
+      - develop
   pull_request:
     branches:
       - "**"
+    types:
+      - reopened
+      - ready_for_review
+      - synchronize
 
 jobs:
   main:
+    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -23,5 +28,12 @@ jobs:
 
       - name: Test the code
         run: |
-          scarb test
+          # Run the test and capture the output
+          output=$(scarb test)
+
+          # Echo the entire output (optional, for debugging purposes)
+          echo "$output"
+
+          # Filter and echo the specific part of the output you are interested in
+          echo "$output" | grep -E "Error: test result: FAILED. [0-9]+ passed; [0-9]+ failed; [0-9]+ ignored"
 
